import type { Country } from '../types';

export const countries: Country[] = [
  { name: 'Afghanistan', code: 'AF', currency: { code: 'AFN', name: 'Afghan afghani', symbol: '؋' } },
  { name: 'Åland Islands', code: 'AX', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Albania', code: 'AL', currency: { code: 'ALL', name: 'Albanian lek', symbol: 'L' } },
  { name: 'Algeria', code: 'DZ', currency: { code: 'DZD', name: 'Algerian dinar', symbol: 'د.ج' } },
  { name: 'American Samoa', code: 'AS', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Andorra', code: 'AD', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Angola', code: 'AO', currency: { code: 'AOA', name: 'Angolan kwanza', symbol: 'Kz' } },
  { name: 'Anguilla', code: 'AI', currency: { code: 'XCD', name: 'East Caribbean dollar', symbol: '$' } },
  { name: 'Antarctica', code: 'AQ', currency: { code: 'AUD', name: 'Australian dollar', symbol: '$' } },
  { name: 'Antigua and Barbuda', code: 'AG', currency: { code: 'XCD', name: 'East Caribbean dollar', symbol: '$' } },
  { name: 'Argentina', code: 'AR', currency: { code: 'ARS', name: 'Argentine peso', symbol: '$' } },
  { name: 'Armenia', code: 'AM', currency: { code: 'AMD', name: 'Armenian dram', symbol: '֏' } },
  { name: 'Aruba', code: 'AW', currency: { code: 'AWG', name: 'Aruban florin', symbol: 'ƒ' } },
  { name: 'Australia', code: 'AU', currency: { code: 'AUD', name: 'Australian dollar', symbol: '$' } },
  { name: 'Austria', code: 'AT', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Azerbaijan', code: 'AZ', currency: { code: 'AZN', name: 'Azerbaijani manat', symbol: '₼' } },
  { name: 'Bahamas', code: 'BS', currency: { code: 'BSD', name: 'Bahamian dollar', symbol: '$' } },
  { name: 'Bahrain', code: 'BH', currency: { code: 'BHD', name: 'Bahraini dinar', symbol: '.د.ب' } },
  { name: 'Bangladesh', code: 'BD', currency: { code: 'BDT', name: 'Bangladeshi taka', symbol: '৳' } },
  { name: 'Barbados', code: 'BB', currency: { code: 'BBD', name: 'Barbadian dollar', symbol: '$' } },
  { name: 'Belarus', code: 'BY', currency: { code: 'BYN', name: 'Belarusian ruble', symbol: 'Br' } },
  { name: 'Belgium', code: 'BE', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Belize', code: 'BZ', currency: { code: 'BZD', name: 'Belize dollar', symbol: '$' } },
  { name: 'Benin', code: 'BJ', currency: { code: 'XOF', name: 'West African CFA franc', symbol: 'Fr' } },
  { name: 'Bermuda', code: 'BM', currency: { code: 'BMD', name: 'Bermudian dollar', symbol: '$' } },
  { name: 'Bhutan', code: 'BT', currency: { code: 'BTN', name: 'Bhutanese ngultrum', symbol: 'Nu.' } },
  { name: 'Bolivia', code: 'BO', currency: { code: 'BOB', name: 'Bolivian boliviano', symbol: 'Bs.' } },
  { name: 'Bosnia and Herzegovina', code: 'BA', currency: { code: 'BAM', name: 'Bosnia and Herzegovina convertible mark', symbol: 'KM' } },
  { name: 'Botswana', code: 'BW', currency: { code: 'BWP', name: 'Botswana pula', symbol: 'P' } },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR', currency: { code: 'BRL', name: 'Brazilian real', symbol: 'R$' } },
  { name: 'British Indian Ocean Territory', code: 'IO', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Brunei Darussalam', code: 'BN', currency: { code: 'BND', name: 'Brunei dollar', symbol: '$' } },
  { name: 'Bulgaria', code: 'BG', currency: { code: 'BGN', name: 'Bulgarian lev', symbol: 'лв' } },
  { name: 'Burkina Faso', code: 'BF', currency: { code: 'XOF', name: 'West African CFA franc', symbol: 'Fr' } },
  { name: 'Burundi', code: 'BI', currency: { code: 'BIF', name: 'Burundian franc', symbol: 'Fr' } },
  { name: 'Cambodia', code: 'KH', currency: { code: 'KHR', name: 'Cambodian riel', symbol: '៛' } },
  { name: 'Cameroon', code: 'CM', currency: { code: 'XAF', name: 'Central African CFA franc', symbol: 'Fr' } },
  { name: 'Canada', code: 'CA', currency: { code: 'CAD', name: 'Canadian dollar', symbol: '$' } },
  { name: 'Cape Verde', code: 'CV', currency: { code: 'CVE', name: 'Cape Verdean escudo', symbol: 'Esc' } },
  { name: 'Cayman Islands', code: 'KY', currency: { code: 'KYD', name: 'Cayman Islands dollar', symbol: '$' } },
  { name: 'Central African Republic', code: 'CF', currency: { code: 'XAF', name: 'Central African CFA franc', symbol: 'Fr' } },
  { name: 'Chad', code: 'TD', currency: { code: 'XAF', name: 'Central African CFA franc', symbol: 'Fr' } },
  { name: 'Chile', code: 'CL', currency: { code: 'CLP', name: 'Chilean peso', symbol: '$' } },
  { name: 'China', code: 'CN', currency: { code: 'CNY', name: 'Chinese yuan', symbol: '¥' } },
  { name: 'Christmas Island', code: 'CX', currency: { code: 'AUD', name: 'Australian dollar', symbol: '$' } },
  { name: 'Cocos (Keeling) Islands', code: 'CC', currency: { code: 'AUD', name: 'Australian dollar', symbol: '$' } },
  { name: 'Colombia', code: 'CO', currency: { code: 'COP', name: 'Colombian peso', symbol: '$' } },
  { name: 'Comoros', code: 'KM', currency: { code: 'KMF', name: 'Comorian franc', symbol: 'Fr' } },
  { name: 'Congo', code: 'CG', currency: { code: 'XAF', name: 'Central African CFA franc', symbol: 'Fr' } },
  { name: 'Congo, The Democratic Republic of the', code: 'CD', currency: { code: 'CDF', name: 'Congolese franc', symbol: 'Fr' } },
  { name: 'Cook Islands', code: 'CK', currency: { code: 'NZD', name: 'New Zealand dollar', symbol: '$' } },
  { name: 'Costa Rica', code: 'CR', currency: { code: 'CRC', name: 'Costa Rican colón', symbol: '₡' } },
  { name: 'Cote D\'Ivoire', code: 'CI', currency: { code: 'XOF', name: 'West African CFA franc', symbol: 'Fr' } },
  { name: 'Croatia', code: 'HR', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Cuba', code: 'CU', currency: { code: 'CUP', name: 'Cuban peso', symbol: '$' } },
  { name: 'Cyprus', code: 'CY', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Czech Republic', code: 'CZ', currency: { code: 'CZK', name: 'Czech koruna', symbol: 'Kč' } },
  { name: 'Denmark', code: 'DK', currency: { code: 'DKK', name: 'Danish krone', symbol: 'kr' } },
  { name: 'Djibouti', code: 'DJ', currency: { code: 'DJF', name: 'Djiboutian franc', symbol: 'Fr' } },
  { name: 'Dominica', code: 'DM', currency: { code: 'XCD', name: 'East Caribbean dollar', symbol: '$' } },
  { name: 'Dominican Republic', code: 'DO', currency: { code: 'DOP', name: 'Dominican peso', symbol: '$' } },
  { name: 'Ecuador', code: 'EC', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Egypt', code: 'EG', currency: { code: 'EGP', name: 'Egyptian pound', symbol: '£' } },
  { name: 'El Salvador', code: 'SV', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Equatorial Guinea', code: 'GQ', currency: { code: 'XAF', name: 'Central African CFA franc', symbol: 'Fr' } },
  { name: 'Eritrea', code: 'ER', currency: { code: 'ERN', name: 'Eritrean nakfa', symbol: 'Nfk' } },
  { name: 'Estonia', code: 'EE', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Ethiopia', code: 'ET', currency: { code: 'ETB', name: 'Ethiopian birr', symbol: 'Br' } },
  { name: 'Falkland Islands (Malvinas)', code: 'FK', currency: { code: 'FKP', name: 'Falkland Islands pound', symbol: '£' } },
  { name: 'Faroe Islands', code: 'FO', currency: { code: 'DKK', name: 'Danish krone', symbol: 'kr' } },
  { name: 'Fiji', code: 'FJ', currency: { code: 'FJD', name: 'Fijian dollar', symbol: '$' } },
  { name: 'Finland', code: 'FI', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'France', code: 'FR', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'French Guiana', code: 'GF', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'French Polynesia', code: 'PF', currency: { code: 'XPF', name: 'CFP franc', symbol: 'Fr' } },
  { name: 'French Southern Territories', code: 'TF', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Gabon', code: 'GA', currency: { code: 'XAF', name: 'Central African CFA franc', symbol: 'Fr' } },
  { name: 'Gambia', code: 'GM', currency: { code: 'GMD', name: 'Gambian dalasi', symbol: 'D' } },
  { name: 'Georgia', code: 'GE', currency: { code: 'GEL', name: 'Georgian lari', symbol: '₾' } },
  { name: 'Germany', code: 'DE', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Ghana', code: 'GH', currency: { code: 'GHS', name: 'Ghanaian cedi', symbol: '₵' } },
  { name: 'Gibraltar', code: 'GI', currency: { code: 'GIP', name: 'Gibraltar pound', symbol: '£' } },
  { name: 'Greece', code: 'GR', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Greenland', code: 'GL', currency: { code: 'DKK', name: 'Danish krone', symbol: 'kr' } },
  { name: 'Grenada', code: 'GD', currency: { code: 'XCD', name: 'East Caribbean dollar', symbol: '$' } },
  { name: 'Guadeloupe', code: 'GP', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Guam', code: 'GU', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Guatemala', code: 'GT', currency: { code: 'GTQ', name: 'Guatemalan quetzal', symbol: 'Q' } },
  { name: 'Guernsey', code: 'GG', currency: { code: 'GBP', name: 'British pound', symbol: '£' } },
  { name: 'Guinea', code: 'GN', currency: { code: 'GNF', name: 'Guinean franc', symbol: 'Fr' } },
  { name: 'Guinea-Bissau', code: 'GW', currency: { code: 'XOF', name: 'West African CFA franc', symbol: 'Fr' } },
  { name: 'Guyana', code: 'GY', currency: { code: 'GYD', name: 'Guyanese dollar', symbol: '$' } },
  { name: 'Haiti', code: 'HT', currency: { code: 'HTG', name: 'Haitian gourde', symbol: 'G' } },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM', currency: { code: 'AUD', name: 'Australian dollar', symbol: '$' } },
  { name: 'Holy See (Vatican City State)', code: 'VA', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Honduras', code: 'HN', currency: { code: 'HNL', name: 'Honduran lempira', symbol: 'L' } },
  { name: 'Hong Kong', code: 'HK', currency: { code: 'HKD', name: 'Hong Kong dollar', symbol: '$' } },
  { name: 'Hungary', code: 'HU', currency: { code: 'HUF', name: 'Hungarian forint', symbol: 'Ft' } },
  { name: 'Iceland', code: 'IS', currency: { code: 'ISK', name: 'Icelandic króna', symbol: 'kr' } },
  { name: 'India', code: 'IN', currency: { code: 'INR', name: 'Indian rupee', symbol: '₹' } },
  { name: 'Indonesia', code: 'ID', currency: { code: 'IDR', name: 'Indonesian rupiah', symbol: 'Rp' } },
  { name: 'Iran, Islamic Republic Of', code: 'IR', currency: { code: 'IRR', name: 'Iranian rial', symbol: '﷼' } },
  { name: 'Iraq', code: 'IQ', currency: { code: 'IQD', name: 'Iraqi dinar', symbol: 'ع.د' } },
  { name: 'Ireland', code: 'IE', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Isle of Man', code: 'IM', currency: { code: 'GBP', name: 'British pound', symbol: '£' } },
  { name: 'Israel', code: 'IL', currency: { code: 'ILS', name: 'Israeli new shekel', symbol: '₪' } },
  { name: 'Italy', code: 'IT', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Jamaica', code: 'JM', currency: { code: 'JMD', name: 'Jamaican dollar', symbol: '$' } },
  { name: 'Japan', code: 'JP', currency: { code: 'JPY', name: 'Japanese yen', symbol: '¥' } },
  { name: 'Jersey', code: 'JE', currency: { code: 'GBP', name: 'British pound', symbol: '£' } },
  { name: 'Jordan', code: 'JO', currency: { code: 'JOD', name: 'Jordanian dinar', symbol: 'د.ا' } },
  { name: 'Kazakhstan', code: 'KZ', currency: { code: 'KZT', name: 'Kazakhstani tenge', symbol: '₸' } },
  { name: 'Kenya', code: 'KE', currency: { code: 'KES', name: 'Kenyan shilling', symbol: 'Sh' } },
  { name: 'Kiribati', code: 'KI', currency: { code: 'AUD', name: 'Australian dollar', symbol: '$' } },
  { name: 'Korea, Democratic People\'S Republic of', code: 'KP', currency: { code: 'KPW', name: 'North Korean won', symbol: '₩' } },
  { name: 'Korea, Republic of', code: 'KR', currency: { code: 'KRW', name: 'South Korean won', symbol: '₩' } },
  { name: 'Kuwait', code: 'KW', currency: { code: 'KWD', name: 'Kuwaiti dinar', symbol: 'د.ك' } },
  { name: 'Kyrgyzstan', code: 'KG', currency: { code: 'KGS', name: 'Kyrgyzstani som', symbol: 'с' } },
  { name: 'Lao People\'S Democratic Republic', code: 'LA', currency: { code: 'LAK', name: 'Lao kip', symbol: '₭' } },
  { name: 'Latvia', code: 'LV', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Lebanon', code: 'LB', currency: { code: 'LBP', name: 'Lebanese pound', symbol: 'ل.ل' } },
  { name: 'Lesotho', code: 'LS', currency: { code: 'LSL', name: 'Lesotho loti', symbol: 'L' } },
  { name: 'Liberia', code: 'LR', currency: { code: 'LRD', name: 'Liberian dollar', symbol: '$' } },
  { name: 'Libyan Arab Jamahiriya', code: 'LY', currency: { code: 'LYD', name: 'Libyan dinar', symbol: 'ل.د' } },
  { name: 'Liechtenstein', code: 'LI', currency: { code: 'CHF', name: 'Swiss franc', symbol: 'Fr' } },
  { name: 'Lithuania', code: 'LT', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Luxembourg', code: 'LU', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Macao', code: 'MO', currency: { code: 'MOP', name: 'Macanese pataca', symbol: 'P' } },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK', currency: { code: 'MKD', name: 'Macedonian denar', symbol: 'ден' } },
  { name: 'Madagascar', code: 'MG', currency: { code: 'MGA', name: 'Malagasy ariary', symbol: 'Ar' } },
  { name: 'Malawi', code: 'MW', currency: { code: 'MWK', name: 'Malawian kwacha', symbol: 'MK' } },
  { name: 'Malaysia', code: 'MY', currency: { code: 'MYR', name: 'Malaysian ringgit', symbol: 'RM' } },
  { name: 'Maldives', code: 'MV', currency: { code: 'MVR', name: 'Maldivian rufiyaa', symbol: '.ރ' } },
  { name: 'Mali', code: 'ML', currency: { code: 'XOF', name: 'West African CFA franc', symbol: 'Fr' } },
  { name: 'Malta', code: 'MT', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Marshall Islands', code: 'MH', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Martinique', code: 'MQ', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Mauritania', code: 'MR', currency: { code: 'MRO', name: 'Mauritanian ouguiya', symbol: 'UM' } },
  { name: 'Mauritius', code: 'MU', currency: { code: 'MUR', name: 'Mauritian rupee', symbol: '₨' } },
  { name: 'Mayotte', code: 'YT', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Mexico', code: 'MX', currency: { code: 'MXN', name: 'Mexican peso', symbol: '$' } },
  { name: 'Micronesia, Federated States of', code: 'FM', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Moldova, Republic of', code: 'MD', currency: { code: 'MDL', name: 'Moldovan leu', symbol: 'L' } },
  { name: 'Monaco', code: 'MC', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Mongolia', code: 'MN', currency: { code: 'MNT', name: 'Mongolian tögrög', symbol: '₮' } },
  { name: 'Montserrat', code: 'MS', currency: { code: 'XCD', name: 'East Caribbean dollar', symbol: '$' } },
  { name: 'Morocco', code: 'MA', currency: { code: 'MAD', name: 'Moroccan dirham', symbol: 'د.م.' } },
  { name: 'Mozambique', code: 'MZ', currency: { code: 'MZN', name: 'Mozambican metical', symbol: 'MT' } },
  { name: 'Myanmar', code: 'MM', currency: { code: 'MMK', name: 'Burmese kyat', symbol: 'Ks' } },
  { name: 'Namibia', code: 'NA', currency: { code: 'NAD', name: 'Namibian dollar', symbol: '$' } },
  { name: 'Nauru', code: 'NR', currency: { code: 'AUD', name: 'Australian dollar', symbol: '$' } },
  { name: 'Nepal', code: 'NP', currency: { code: 'NPR', name: 'Nepalese rupee', symbol: '₨' } },
  { name: 'Netherlands', code: 'NL', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Netherlands Antilles', code: 'AN', currency: { code: 'ANG', name: 'Netherlands Antillean guilder', symbol: 'ƒ' } },
  { name: 'New Caledonia', code: 'NC', currency: { code: 'XPF', name: 'CFP franc', symbol: 'Fr' } },
  { name: 'New Zealand', code: 'NZ', currency: { code: 'NZD', name: 'New Zealand dollar', symbol: '$' } },
  { name: 'Nicaragua', code: 'NI', currency: { code: 'NIO', name: 'Nicaraguan córdoba', symbol: 'C$' } },
  { name: 'Niger', code: 'NE', currency: { code: 'XOF', name: 'West African CFA franc', symbol: 'Fr' } },
  { name: 'Nigeria', code: 'NG', currency: { code: 'NGN', name: 'Nigerian naira', symbol: '₦' } },
  { name: 'Niue', code: 'NU', currency: { code: 'NZD', name: 'New Zealand dollar', symbol: '$' } },
  { name: 'Norfolk Island', code: 'NF', currency: { code: 'AUD', name: 'Australian dollar', symbol: '$' } },
  { name: 'Northern Mariana Islands', code: 'MP', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Norway', code: 'NO', currency: { code: 'NOK', name: 'Norwegian krone', symbol: 'kr' } },
  { name: 'Oman', code: 'OM', currency: { code: 'OMR', name: 'Omani rial', symbol: 'ر.ع.' } },
  { name: 'Pakistan', code: 'PK', currency: { code: 'PKR', name: 'Pakistani rupee', symbol: '₨' } },
  { name: 'Palau', code: 'PW', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Palestinian Territory, Occupied', code: 'PS', currency: { code: 'ILS', name: 'Israeli new shekel', symbol: '₪' } },
  { name: 'Panama', code: 'PA', currency: { code: 'PAB', name: 'Panamanian balboa', symbol: 'B/.' } },
  { name: 'Papua New Guinea', code: 'PG', currency: { code: 'PGK', name: 'Papua New Guinean kina', symbol: 'K' } },
  { name: 'Paraguay', code: 'PY', currency: { code: 'PYG', name: 'Paraguayan guaraní', symbol: '₲' } },
  { name: 'Peru', code: 'PE', currency: { code: 'PEN', name: 'Peruvian sol', symbol: 'S/.' } },
  { name: 'Philippines', code: 'PH', currency: { code: 'PHP', name: 'Philippine peso', symbol: '₱' } },
  { name: 'Pitcairn', code: 'PN', currency: { code: 'NZD', name: 'New Zealand dollar', symbol: '$' } },
  { name: 'Poland', code: 'PL', currency: { code: 'PLN', name: 'Polish złoty', symbol: 'zł' } },
  { name: 'Portugal', code: 'PT', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Puerto Rico', code: 'PR', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Qatar', code: 'QA', currency: { code: 'QAR', name: 'Qatari riyal', symbol: 'ر.ق' } },
  { name: 'Reunion', code: 'RE', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Romania', code: 'RO', currency: { code: 'RON', name: 'Romanian leu', symbol: 'lei' } },
  { name: 'Russian Federation', code: 'RU', currency: { code: 'RUB', name: 'Russian ruble', symbol: '₽' } },
  { name: 'RWANDA', code: 'RW', currency: { code: 'RWF', name: 'Rwandan franc', symbol: 'Fr' } },
  { name: 'Saint Helena', code: 'SH', currency: { code: 'SHP', name: 'Saint Helena pound', symbol: '£' } },
  { name: 'Saint Kitts and Nevis', code: 'KN', currency: { code: 'XCD', name: 'East Caribbean dollar', symbol: '$' } },
  { name: 'Saint Lucia', code: 'LC', currency: { code: 'XCD', name: 'East Caribbean dollar', symbol: '$' } },
  { name: 'Saint Pierre and Miquelon', code: 'PM', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', currency: { code: 'XCD', name: 'East Caribbean dollar', symbol: '$' } },
  { name: 'Samoa', code: 'WS', currency: { code: 'WST', name: 'Samoan tālā', symbol: 'T' } },
  { name: 'San Marino', code: 'SM', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Sao Tome and Principe', code: 'ST', currency: { code: 'STD', name: 'São Tomé and Príncipe dobra', symbol: 'Db' } },
  { name: 'Saudi Arabia', code: 'SA', currency: { code: 'SAR', name: 'Saudi riyal', symbol: 'ر.س' } },
  { name: 'Senegal', code: 'SN', currency: { code: 'XOF', name: 'West African CFA franc', symbol: 'Fr' } },
  { name: 'Serbia and Montenegro', code: 'CS', currency: { code: 'RSD', name: 'Serbian dinar', symbol: 'дин.' } },
  { name: 'Seychelles', code: 'SC', currency: { code: 'SCR', name: 'Seychellois rupee', symbol: '₨' } },
  { name: 'Sierra Leone', code: 'SL', currency: { code: 'SLL', name: 'Sierra Leonean leone', symbol: 'Le' } },
  { name: 'Singapore', code: 'SG', currency: { code: 'SGD', name: 'Singapore dollar', symbol: '$' } },
  { name: 'Slovakia', code: 'SK', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Slovenia', code: 'SI', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Solomon Islands', code: 'SB', currency: { code: 'SBD', name: 'Solomon Islands dollar', symbol: '$' } },
  { name: 'Somalia', code: 'SO', currency: { code: 'SOS', name: 'Somali shilling', symbol: 'Sh' } },
  { name: 'South Africa', code: 'ZA', currency: { code: 'ZAR', name: 'South African rand', symbol: 'R' } },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS', currency: { code: 'GBP', name: 'British pound', symbol: '£' } },
  { name: 'Spain', code: 'ES', currency: { code: 'EUR', name: 'Euro', symbol: '€' } },
  { name: 'Sri Lanka', code: 'LK', currency: { code: 'LKR', name: 'Sri Lankan rupee', symbol: 'Rs' } },
  { name: 'Sudan', code: 'SD', currency: { code: 'SDG', name: 'Sudanese pound', symbol: 'ج.س.' } },
  { name: 'Suriname', code: 'SR', currency: { code: 'SRD', name: 'Surinamese dollar', symbol: '$' } },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', currency: { code: 'NOK', name: 'Norwegian krone', symbol: 'kr' } },
  { name: 'Swaziland', code: 'SZ', currency: { code: 'SZL', name: 'Swazi lilangeni', symbol: 'L' } },
  { name: 'Sweden', code: 'SE', currency: { code: 'SEK', name: 'Swedish krona', symbol: 'kr' } },
  { name: 'Switzerland', code: 'CH', currency: { code: 'CHF', name: 'Swiss franc', symbol: 'Fr' } },
  { name: 'Syrian Arab Republic', code: 'SY', currency: { code: 'SYP', name: 'Syrian pound', symbol: '£' } },
  { name: 'Taiwan, Province of China', code: 'TW', currency: { code: 'TWD', name: 'New Taiwan dollar', symbol: '$' } },
  { name: 'Tajikistan', code: 'TJ', currency: { code: 'TJS', name: 'Tajikistani somoni', symbol: 'ЅМ' } },
  { name: 'Tanzania, United Republic of', code: 'TZ', currency: { code: 'TZS', name: 'Tanzanian shilling', symbol: 'Sh' } },
  { name: 'Thailand', code: 'TH', currency: { code: 'THB', name: 'Thai baht', symbol: '฿' } },
  { name: 'Timor-Leste', code: 'TL', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Togo', code: 'TG', currency: { code: 'XOF', name: 'West African CFA franc', symbol: 'Fr' } },
  { name: 'Tokelau', code: 'TK', currency: { code: 'NZD', name: 'New Zealand dollar', symbol: '$' } },
  { name: 'Tonga', code: 'TO', currency: { code: 'TOP', name: 'Tongan paʻanga', symbol: 'T$' } },
  { name: 'Trinidad and Tobago', code: 'TT', currency: { code: 'TTD', name: 'Trinidad and Tobago dollar', symbol: '$' } },
  { name: 'Tunisia', code: 'TN', currency: { code: 'TND', name: 'Tunisian dinar', symbol: 'د.ت' } },
  { name: 'Turkey', code: 'TR', currency: { code: 'TRY', name: 'Turkish lira', symbol: '₺' } },
  { name: 'Turkmenistan', code: 'TM', currency: { code: 'TMT', name: 'Turkmenistan manat', symbol: 'm' } },
  { name: 'Turks and Caicos Islands', code: 'TC', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Tuvalu', code: 'TV', currency: { code: 'AUD', name: 'Australian dollar', symbol: '$' } },
  { name: 'Uganda', code: 'UG', currency: { code: 'UGX', name: 'Ugandan shilling', symbol: 'Sh' } },
  { name: 'Ukraine', code: 'UA', currency: { code: 'UAH', name: 'Ukrainian hryvnia', symbol: '₴' } },
  { name: 'United Arab Emirates', code: 'AE', currency: { code: 'AED', name: 'United Arab Emirates dirham', symbol: 'د.إ' } },
  { name: 'United Kingdom', code: 'GB', currency: { code: 'GBP', name: 'British pound', symbol: '£' } },
  { name: 'United States', code: 'US', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'United States Minor Outlying Islands', code: 'UM', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Uruguay', code: 'UY', currency: { code: 'UYU', name: 'Uruguayan peso', symbol: '$' } },
  { name: 'Uzbekistan', code: 'UZ', currency: { code: 'UZS', name: 'Uzbekistani soʻm', symbol: 'soʻm' } },
  { name: 'Vanuatu', code: 'VU', currency: { code: 'VUV', name: 'Vanuatu vatu', symbol: 'Vt' } },
  { name: 'Venezuela', code: 'VE', currency: { code: 'VEF', name: 'Venezuelan bolívar', symbol: 'Bs F' } },
  { name: 'Viet Nam', code: 'VN', currency: { code: 'VND', name: 'Vietnamese đồng', symbol: '₫' } },
  { name: 'Virgin Islands, British', code: 'VG', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Virgin Islands, U.S.', code: 'VI', currency: { code: 'USD', name: 'United States Dollar', symbol: '$' } },
  { name: 'Wallis and Futuna', code: 'WF', currency: { code: 'XPF', name: 'CFP franc', symbol: 'Fr' } },
  { name: 'Western Sahara', code: 'EH', currency: { code: 'MAD', name: 'Moroccan dirham', symbol: 'د.م.' } },
  { name: 'Yemen', code: 'YE', currency: { code: 'YER', name: 'Yemeni rial', symbol: '﷼' } },
  { name: 'Zambia', code: 'ZM', currency: { code: 'ZMW', name: 'Zambian kwacha', symbol: 'ZK' } },
  { name: 'Zimbabwe', code: 'ZW', currency: { code: 'ZWL', name: 'Zimbabwean dollar', symbol: '$' } },
].sort((a, b) => a.name.localeCompare(b.name));